### PR TITLE
Increasing Ball Velocity Over Time

### PR DESCRIPTION
**Pull request by frich98**
- Defined currently in Player Supervisor
- Player can define the following:

1. Starting game speed
2. How frequently the game speed increases (i.e., every x seconds)
3. By what % the game speed increases when it does (% here are 1 through 100, converted to decimal in game)

This was the most intuitive way I could find to increase the ball's velocity. If we want more randomness in there, I could work on little "bursts" of speed for the ball throughout the game, and have the player be able to turn off incremental game speed increases. That could be v2. 

Let me know if you run across any issues.

### CODE REVIEW

**Review by jonoco — COMMENTED** [review]
The trouble with changing the time scale is many things you probably don't want to speed up are also effected by the time scale, like paddle movement, particles and audio clip playback. If the goal is to speed up the ball, it would be simpler to multiply the ball's rigidbody velocity by a scalar.

**Comment by frich98** [comment]
Instead of adjusting the game velocity using Time.timeScale, I adjusted the ball's rigid body velocity instead per the suggestion above. This produces the desired result without impacting other game objects. The two variables the user can adjust above still apply. I also did a little refactoring of the ball velocity increase code to make it easier to read through.

**Comment by frich98** [comment]
1) On ball, updated collision detection to continuous (From discrete) to help with avoiding the ball moving through barriers without collision at higher speeds.  (link Chase provided for more info on change: (https://forum.unity.com/threads/what-are-the-necessary-settings-to-prevent-objects-passing-through-each-other-at-high-speeds.384519/)

2)updated the Player Supervisor code to only call IncreaseBallSpeed if the ball object has not been destroyed yet. Was getting rigid body can't be accessed errors without this line of code.

**Review by matzingc — DISMISSED** [review]
Looks good!

**Comment by frich98** [comment]
Closing this merge request. Will make a new one with fresh changes to the new integrated ml agent main script.

**Pull request closed without merging**
