### PR TITLE
Menu UI Update

### PR DESCRIPTION
**Pull request by jonoco**
- Added intro video
- Updated menus for new theme
- Added game mode selection screens

### CODE REVIEW

**Review by matzingc — DISMISSED** [review]
Great work! These updates look awesome. I can wire up the following buttons once this and my current pull request are merged in:
- Single player select: Watch AI
- Multi player select: Play to lose, play to win

**Comment by frich98** [comment]
Yeah, I definitely concur with Chase -  this looks pretty darn awesome!

**Comment by jonoco** [comment]
Merged main into the branch and opened it for merging.

**Review by matzingc — APPROVED** [review]
Looks good!

**Pull request merged**
